### ISSUE TITLE
Outdated .lex file

### ISSUE THREAD

**Issue by pini-gh** [cliftonlabs/json-simple#24]
Hi,
The .lex file provided ith this source tree is not valid anymore since jflex release 1.6.0. The '%table' code generation method was deprecated in jflex 1.5.0 and suppressed in 1.6.0:
https://jflex.de/history.html

Using the default '%pack' method generates a valid Yylex.java file, but the resulting build fails the tests:
```
[INFO] Running com.github.cliftonlabs.json_simple.JsonerTest
[ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 s <<< FAILURE! - in com.github.cliftonlabs.json_simple.JsonerTest
[ERROR] testStringDeserialization(com.github.cliftonlabs.json_simple.JsonerTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: Index 1050 out of bounds for length 128
        at com.github.cliftonlabs.json_simple.JsonerTest.testStringDeserialization(JsonerTest.java:466)

[INFO] Running com.github.cliftonlabs.json_simple.JsonObjectTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.github.cliftonlabs.json_simple.JsonObjectTest
[INFO] Running com.github.cliftonlabs.json_simple.YylexTest
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in com.github.cliftonlabs.json_simple.YylexTest
[ERROR] testLexingStringContainingEscapedCharacters(com.github.cliftonlabs.json_simple.YylexTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: Index 1050 out of bounds for length 128
        at com.github.cliftonlabs.json_simple.YylexTest.testLexingStringContainingEscapedCharacters(YylexTest.java:161)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JsonerTest.testStringDeserialization:466 » ArrayIndexOutOfBounds Index 1050 ou...
[ERROR]   YylexTest.testLexingStringContainingEscapedCharacters:161 » ArrayIndexOutOfBounds
[INFO] 
[ERROR] Tests run: 39, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by pini-gh** [comment]
**Update**: I must have mixed things in my previous attempts. The test cases are successful eventually.
It just needs removing the deprecated '%table' statement.

**Comment by loegering** [comment]
Thanks for bringing this to my attention. I've replaced %table with %pack to explicitly use the default behavior and confirmed the generated Yylex file works with the tests. Cheers!
